# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  employeeapi:
    image: employeeapi
    build:
      context: .
      dockerfile: Employee.API/Dockerfile
    ports:
      - 8001:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
